-- =====================================================================
-- MindCluster / SafeDiary - reference database schema (PostgreSQL 16+)
-- =====================================================================
-- Single source of truth for the target model. Read docs/database/README.md
-- before changing anything here.
--
-- Conventions (summary):
--   * One PostgreSQL schema per bounded context; the context owns its tables.
--   * PK: id BIGINT identity (matches AuditableAbstractAggregateRoot).
--   * Every table: created_at / updated_at timestamptz (audit/event logs: only occurred_at).
--   * Enums: VARCHAR + CHECK with UPPER_SNAKE values (same as Java enums).
--   * Foreign keys ONLY inside the same schema. Other contexts are referenced
--     by id (account_id, alias_id...) without a FK constraint.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS iam;
CREATE SCHEMA IF NOT EXISTS profiles;
CREATE SCHEMA IF NOT EXISTS diary;
CREATE SCHEMA IF NOT EXISTS assistantai;
CREATE SCHEMA IF NOT EXISTS communities;
CREATE SCHEMA IF NOT EXISTS routines;

-- =====================================================================
-- IAM: identity, authentication, devices, consent and security audit
-- =====================================================================

CREATE TABLE iam.accounts (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                  VARCHAR(254) NOT NULL,
    password_hash          VARCHAR(100),                 -- NULL when the account only uses an external provider
    role                   VARCHAR(20)  NOT NULL CHECK (role IN ('PATIENT', 'SPECIALIST', 'ADMIN')),
    status                 VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE'
                           CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED')),
    failed_login_attempts  SMALLINT     NOT NULL DEFAULT 0 CHECK (failed_login_attempts >= 0),
    locked_until           TIMESTAMPTZ,                  -- policy: 5 failed attempts => temporary lock
    last_login_at          TIMESTAMPTZ,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_accounts_email ON iam.accounts (lower(email));

CREATE TABLE iam.auth_providers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     BIGINT      NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    provider_type  VARCHAR(20) NOT NULL CHECK (provider_type IN ('GOOGLE', 'APPLE')),
    external_id    VARCHAR(255) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_auth_providers_external UNIQUE (provider_type, external_id)
);
CREATE INDEX ix_auth_providers_account ON iam.auth_providers (account_id);

-- One row per physical device: biometric unlock + push token live here.
CREATE TABLE iam.devices (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id         BIGINT       NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    device_identifier  VARCHAR(128) NOT NULL,
    platform           VARCHAR(10)  NOT NULL CHECK (platform IN ('ANDROID', 'IOS', 'WEB')),
    push_token         VARCHAR(512),
    biometric_enabled  BOOLEAN      NOT NULL DEFAULT FALSE,
    last_seen_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ux_devices_account_device UNIQUE (account_id, device_identifier)
);

-- Policy: logout invalidates the device token => revoked_at.
CREATE TABLE iam.refresh_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT      NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    device_id    BIGINT      REFERENCES iam.devices (id) ON DELETE CASCADE,
    token_hash   CHAR(64)    NOT NULL UNIQUE,            -- SHA-256, never the raw token
    expires_at   TIMESTAMPTZ NOT NULL,
    revoked_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_refresh_tokens_account ON iam.refresh_tokens (account_id);

-- Policy: single-use link that expires after 30 minutes.
CREATE TABLE iam.password_reset_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT      NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    token_hash   CHAR(64)    NOT NULL UNIQUE,
    expires_at   TIMESTAMPTZ NOT NULL,
    used_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_password_reset_tokens_account ON iam.password_reset_tokens (account_id);

-- "Identidad de especialista verificada (por parte de la administración)".
CREATE TABLE iam.specialist_verifications (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id              BIGINT       NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    license_number          VARCHAR(50)  NOT NULL,       -- e.g. CPsP number
    document_url            VARCHAR(512),
    status                  VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                            CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    submitted_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    reviewed_by_account_id  BIGINT       REFERENCES iam.accounts (id),
    reviewed_at             TIMESTAMPTZ,
    rejection_reason        VARCHAR(500),
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_specialist_verifications_account ON iam.specialist_verifications (account_id);

-- Patient -> specialist consent to see the emotional history.
CREATE TABLE iam.consents (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_account_id     BIGINT      NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    specialist_account_id  BIGINT      NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    status                 VARCHAR(10) NOT NULL DEFAULT 'GRANTED' CHECK (status IN ('GRANTED', 'REVOKED')),
    shares_from            DATE,                          -- NULL = the whole history
    shares_until           DATE,
    granted_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at             TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_consents_distinct_accounts CHECK (patient_account_id <> specialist_account_id),
    CONSTRAINT ck_consents_period CHECK (shares_until IS NULL OR shares_from IS NULL OR shares_until >= shares_from),
    CONSTRAINT ck_consents_revoked CHECK ((status = 'REVOKED') = (revoked_at IS NOT NULL))
);
-- Only one active consent per patient/specialist pair.
CREATE UNIQUE INDEX ux_consents_active_pair ON iam.consents (patient_account_id, specialist_account_id)
    WHERE status = 'GRANTED';
CREATE INDEX ix_consents_specialist ON iam.consents (specialist_account_id) WHERE status = 'GRANTED';

-- What the consent covers.
CREATE TABLE iam.consent_scopes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_id  BIGINT      NOT NULL REFERENCES iam.consents (id) ON DELETE CASCADE,
    scope       VARCHAR(30) NOT NULL CHECK (scope IN ('DIARY_ENTRIES', 'MOOD_CHECK_INS', 'AI_CLINICAL_SUMMARIES')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_consent_scopes UNIQUE (consent_id, scope)
);

-- Append-only security log (consents, crisis protocol, logins...). Never UPDATE or DELETE.
CREATE TABLE iam.audit_events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_account_id   BIGINT,                           -- NULL when the system acts
    target_account_id  BIGINT,
    action             VARCHAR(60)  NOT NULL,            -- CONSENT_GRANTED, CONSENT_REVOKED, CRISIS_PROTOCOL_ACTIVATED...
    source_context     VARCHAR(30)  NOT NULL,            -- iam, profiles, diary, assistantai, communities, routines
    resource_type      VARCHAR(60),
    resource_id        BIGINT,
    metadata           JSONB,
    occurred_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_events_target ON iam.audit_events (target_account_id, occurred_at DESC);

-- =====================================================================
-- PROFILES: personal profile, preferences, clinicians, community alias
-- =====================================================================

-- Created automatically when IAM publishes "Cuenta de usuario registrada".
CREATE TABLE profiles.user_profiles (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id                   BIGINT       NOT NULL UNIQUE,   -- -> iam.accounts (no FK: other context)
    display_name                 VARCHAR(80)  NOT NULL,
    avatar_url                   VARCHAR(512),
    birth_date                   DATE,
    locale                       VARCHAR(10)  NOT NULL DEFAULT 'es-PE',
    timezone                     VARCHAR(40)  NOT NULL DEFAULT 'America/Lima',
    ai_tone_preference           VARCHAR(20)  NOT NULL DEFAULT 'EMPATHIC'
                                 CHECK (ai_tone_preference IN ('EMPATHIC', 'REFLECTIVE', 'ANALYTICAL', 'CALM')),
    proactive_follow_up_enabled  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at                   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE profiles.notification_preferences (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id            BIGINT      NOT NULL UNIQUE REFERENCES profiles.user_profiles (id) ON DELETE CASCADE,
    push_enabled          BOOLEAN     NOT NULL DEFAULT TRUE,
    email_enabled         BOOLEAN     NOT NULL DEFAULT FALSE,
    quiet_hours_start     TIME,
    quiet_hours_end       TIME,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Public directory card of a specialist (verification itself lives in iam.specialist_verifications).
CREATE TABLE profiles.clinician_profiles (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id                BIGINT        NOT NULL UNIQUE,
    professional_title        VARCHAR(120)  NOT NULL,
    bio                       TEXT,
    years_of_experience       SMALLINT      CHECK (years_of_experience >= 0),
    session_duration_minutes  SMALLINT      NOT NULL DEFAULT 50 CHECK (session_duration_minutes > 0),
    hourly_rate               NUMERIC(10, 2) CHECK (hourly_rate >= 0),
    currency                  CHAR(3)       NOT NULL DEFAULT 'PEN',
    insurance_accepted        BOOLEAN       NOT NULL DEFAULT FALSE,
    published_in_directory    BOOLEAN       NOT NULL DEFAULT FALSE,
    rating_average            NUMERIC(3, 2) CHECK (rating_average BETWEEN 0 AND 5),
    review_count              INTEGER       NOT NULL DEFAULT 0 CHECK (review_count >= 0),
    created_at                TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE profiles.clinician_specialties (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_profile_id  BIGINT      NOT NULL REFERENCES profiles.clinician_profiles (id) ON DELETE CASCADE,
    specialty             VARCHAR(80) NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_clinician_specialties UNIQUE (clinician_profile_id, specialty)
);

CREATE TABLE profiles.clinician_availability_windows (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_profile_id  BIGINT      NOT NULL REFERENCES profiles.clinician_profiles (id) ON DELETE CASCADE,
    day_of_week           SMALLINT    NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),  -- ISO: 1 = Monday
    start_time            TIME        NOT NULL,
    end_time              TIME        NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_availability_range CHECK (end_time > start_time)
);
CREATE INDEX ix_availability_clinician ON profiles.clinician_availability_windows (clinician_profile_id);

-- "Sincronización de calendario externo completada" (Google Calendar / Outlook).
CREATE TABLE profiles.calendar_connections (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_profile_id     BIGINT       NOT NULL REFERENCES profiles.clinician_profiles (id) ON DELETE CASCADE,
    provider                 VARCHAR(20)  NOT NULL CHECK (provider IN ('GOOGLE', 'OUTLOOK')),
    external_calendar_id     VARCHAR(255) NOT NULL,
    refresh_token_encrypted  BYTEA        NOT NULL,      -- encrypted by the application, never plain text
    status                   VARCHAR(20)  NOT NULL DEFAULT 'CONNECTED'
                             CHECK (status IN ('CONNECTED', 'DISCONNECTED', 'ERROR')),
    last_synced_at           TIMESTAMPTZ,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ux_calendar_connections UNIQUE (clinician_profile_id, provider)
);

CREATE TABLE profiles.saved_specialists (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id            BIGINT      NOT NULL REFERENCES profiles.user_profiles (id) ON DELETE CASCADE,
    clinician_profile_id  BIGINT      NOT NULL REFERENCES profiles.clinician_profiles (id) ON DELETE CASCADE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_saved_specialists UNIQUE (profile_id, clinician_profile_id)
);

-- The ONLY place that links an anonymous alias to a real account.
-- Communities stores alias_id only and never sees account_id.
CREATE TABLE profiles.community_aliases (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id         BIGINT      NOT NULL,
    handle             VARCHAR(40) NOT NULL,
    avatar_url         VARCHAR(512),
    voice_mask_preset  VARCHAR(20)  CHECK (voice_mask_preset IN ('NONE', 'LOW', 'HIGH', 'ROBOTIC')),
    active             BOOLEAN     NOT NULL DEFAULT TRUE,
    rotated_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_community_aliases_handle ON profiles.community_aliases (lower(handle));
CREATE UNIQUE INDEX ux_community_aliases_one_active ON profiles.community_aliases (account_id) WHERE active;

-- =====================================================================
-- DIARY: entries (text/voice), factors, attachments, mood, vault, streaks
-- =====================================================================

CREATE TABLE diary.private_vaults (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT       NOT NULL UNIQUE,
    pin_hash    VARCHAR(100) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE diary.diary_entries (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id              BIGINT       NOT NULL,
    vault_id                BIGINT       REFERENCES diary.private_vaults (id) ON DELETE SET NULL,  -- "Entrada movida a Bóveda Privada"
    entry_type              VARCHAR(10)  NOT NULL CHECK (entry_type IN ('TEXT', 'VOICE')),
    title                   VARCHAR(150),
    content                 TEXT,                         -- text, or transcription of a voice note
    audio_url               VARCHAR(512),
    audio_duration_seconds  INTEGER      CHECK (audio_duration_seconds > 0),
    transcription_status    VARCHAR(20)  CHECK (transcription_status IN ('PENDING', 'COMPLETED', 'FAILED')),
    primary_emotion         VARCHAR(20)  CHECK (primary_emotion IN
                            ('APPREHENSION', 'ACCEPTANCE', 'ANNOYANCE', 'VIGILANCE', 'PENSIVENESS', 'SERENITY', 'JOY', 'SADNESS', 'FEAR')),
    emotion_confirmed       BOOLEAN      NOT NULL DEFAULT FALSE,  -- Emotion Tag: suggested by AI until the user confirms
    emotional_intensity     SMALLINT     CHECK (emotional_intensity BETWEEN 1 AND 10),
    ai_reflection           TEXT,                         -- filled by "ReflectionGenerated" from AssistantAI
    is_sensitive            BOOLEAN      NOT NULL DEFAULT FALSE,
    status                  VARCHAR(10)  NOT NULL DEFAULT 'SAVED' CHECK (status IN ('DRAFT', 'SAVED', 'DELETED')),
    written_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_diary_entries_body CHECK (
        (entry_type = 'TEXT' AND content IS NOT NULL) OR (entry_type = 'VOICE' AND audio_url IS NOT NULL))
);
CREATE INDEX ix_diary_entries_account_written ON diary.diary_entries (account_id, written_at DESC)
    WHERE status <> 'DELETED';

CREATE TABLE diary.entry_tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id    BIGINT      NOT NULL REFERENCES diary.diary_entries (id) ON DELETE CASCADE,
    tag         VARCHAR(40) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_entry_tags UNIQUE (entry_id, tag)
);

-- "Factor externo (clima, sueño, etc.) etiquetado a una entrada".
CREATE TABLE diary.external_factors (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id         BIGINT       NOT NULL UNIQUE REFERENCES diary.diary_entries (id) ON DELETE CASCADE,
    sleep_hours      NUMERIC(3, 1) CHECK (sleep_hours BETWEEN 0 AND 24),
    energy_level     VARCHAR(10)  CHECK (energy_level IN ('LOW', 'MEDIUM', 'HIGH')),
    stress_level     VARCHAR(10)  CHECK (stress_level IN ('LOW', 'MEDIUM', 'HIGH')),
    weather          VARCHAR(20)  CHECK (weather IN ('SUNNY', 'CLOUDY', 'RAINY', 'COLD', 'HOT')),
    caffeine_intake  VARCHAR(10)  CHECK (caffeine_intake IN ('NONE', 'LOW', 'MEDIUM', 'HIGH')),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- "Archivos multimedia asociados".
CREATE TABLE diary.entry_attachments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id    BIGINT       NOT NULL REFERENCES diary.diary_entries (id) ON DELETE CASCADE,
    file_url    VARCHAR(512) NOT NULL,
    media_type  VARCHAR(100) NOT NULL,                   -- MIME type
    size_bytes  BIGINT       NOT NULL CHECK (size_bytes > 0),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_entry_attachments_entry ON diary.entry_attachments (entry_id);

-- "Estado de ánimo diario registrado".
CREATE TABLE diary.mood_check_ins (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     BIGINT      NOT NULL,
    emotion        VARCHAR(20) NOT NULL CHECK (emotion IN
                   ('APPREHENSION', 'ACCEPTANCE', 'ANNOYANCE', 'VIGILANCE', 'PENSIVENESS', 'SERENITY', 'JOY', 'SADNESS', 'FEAR')),
    valence_score  SMALLINT    NOT NULL CHECK (valence_score BETWEEN -5 AND 5),
    energy_score   SMALLINT    CHECK (energy_score BETWEEN 1 AND 10),
    logged_on      DATE        NOT NULL,
    logged_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_mood_check_ins_daily UNIQUE (account_id, logged_on)
);

CREATE TABLE diary.streaks (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id              BIGINT      NOT NULL UNIQUE,
    current_streak_days     INTEGER     NOT NULL DEFAULT 0 CHECK (current_streak_days >= 0),
    longest_streak_days     INTEGER     NOT NULL DEFAULT 0 CHECK (longest_streak_days >= 0),
    last_log_date           DATE,
    freeze_tokens_available SMALLINT    NOT NULL DEFAULT 0 CHECK (freeze_tokens_available >= 0),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- "Insignia de racha de registro desbloqueada".
CREATE TABLE diary.badges (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT      NOT NULL,
    badge_type   VARCHAR(30) NOT NULL CHECK (badge_type IN ('STREAK_7', 'STREAK_30', 'STREAK_100', 'FIRST_VOICE_NOTE')),
    unlocked_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_badges UNIQUE (account_id, badge_type)
);

-- =====================================================================
-- ASSISTANTAI: conversations, emotion, distortions, risk, clinical summary
-- (already implemented in the backend; keep column names in sync with the JPA entities)
-- =====================================================================

CREATE TABLE assistantai.conversation_sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT      NOT NULL,
    started_at    TIMESTAMPTZ NOT NULL,
    ended_at      TIMESTAMPTZ,
    status        VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'CLOSED', 'CRISIS_TRIGGERED')),
    current_tone  VARCHAR(20) NOT NULL CHECK (current_tone IN ('EMPATHIC', 'REFLECTIVE', 'ANALYTICAL', 'CALM')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_conversation_sessions_account ON assistantai.conversation_sessions (account_id, started_at DESC);

CREATE TABLE assistantai.conversation_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT      NOT NULL REFERENCES assistantai.conversation_sessions (id) ON DELETE CASCADE,
    sender       VARCHAR(10) NOT NULL CHECK (sender IN ('USER', 'AI')),
    content      TEXT        NOT NULL,
    emotion_tag  VARCHAR(20) CHECK (emotion_tag IN
                 ('APPREHENSION', 'ACCEPTANCE', 'ANNOYANCE', 'VIGILANCE', 'PENSIVENESS', 'SERENITY', 'JOY', 'SADNESS', 'FEAR')),
    sent_at      TIMESTAMPTZ NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_conversation_messages_session ON assistantai.conversation_messages (session_id, sent_at);

CREATE TABLE assistantai.cognitive_distortions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT       NOT NULL REFERENCES assistantai.conversation_messages (id) ON DELETE CASCADE,
    type        VARCHAR(30)  NOT NULL CHECK (type IN
                ('CATASTROPHIZING', 'OVERGENERALIZATION', 'ALL_OR_NOTHING', 'EMOTIONAL_REASONING', 'MENTAL_FILTER')),
    evidence    VARCHAR(300),
    confidence  DOUBLE PRECISION NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_cognitive_distortions_message ON assistantai.cognitive_distortions (message_id);

-- One assessment per evaluated user message (a session has many).
CREATE TABLE assistantai.risk_assessments (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id                 BIGINT       NOT NULL REFERENCES assistantai.conversation_sessions (id) ON DELETE CASCADE,
    message_id                 BIGINT       REFERENCES assistantai.conversation_messages (id) ON DELETE SET NULL,
    risk_score                 DOUBLE PRECISION NOT NULL CHECK (risk_score BETWEEN 0 AND 1),
    risk_level                 VARCHAR(10)  NOT NULL CHECK (risk_level IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')),
    trigger_keywords           VARCHAR(500),
    crisis_protocol_activated  BOOLEAN      NOT NULL DEFAULT FALSE,
    assessed_at                TIMESTAMPTZ  NOT NULL,
    created_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                 TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_risk_assessments_session ON assistantai.risk_assessments (session_id, assessed_at DESC);
CREATE INDEX ix_risk_assessments_crisis ON assistantai.risk_assessments (assessed_at DESC)
    WHERE crisis_protocol_activated;

-- Weekly summary for the specialist. Only visible with an iam.consents scope AI_CLINICAL_SUMMARIES.
CREATE TABLE assistantai.clinical_summaries (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id           BIGINT       NOT NULL,
    period_start         DATE         NOT NULL,
    period_end           DATE         NOT NULL,
    dominant_emotions    VARCHAR(200),
    key_triggers         TEXT,
    synthesis_narrative  TEXT         NOT NULL,
    highlights           TEXT,
    generated_at         TIMESTAMPTZ  NOT NULL,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_clinical_summaries_period CHECK (period_end >= period_start),
    CONSTRAINT ux_clinical_summaries_period UNIQUE (account_id, period_start, period_end)
);

-- =====================================================================
-- COMMUNITIES: anonymous real-time support rooms (absorbs the old "Rooms" context)
-- Only alias ids appear here. No account_id, no raw audio.
-- =====================================================================

CREATE TABLE communities.rooms (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_alias_id         BIGINT       NOT NULL,          -- -> profiles.community_aliases
    title                 VARCHAR(100) NOT NULL,
    topic                 VARCHAR(60)  NOT NULL,
    description           TEXT,
    room_type             VARCHAR(20)  NOT NULL DEFAULT 'PEER'
                          CHECK (room_type IN ('PEER', 'PROFESSIONAL_GROUP')),  -- group session led by a psychologist
    lifecycle             VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED'
                          CHECK (lifecycle IN ('SCHEDULED', 'OPEN', 'CLOSED', 'CANCELLED')),
    capacity              SMALLINT     NOT NULL CHECK (capacity BETWEEN 2 AND 200),
    time_limit_minutes    SMALLINT     CHECK (time_limit_minutes BETWEEN 5 AND 240),
    scheduled_at          TIMESTAMPTZ,
    opened_at             TIMESTAMPTZ,
    closed_at             TIMESTAMPTZ,
    version               INTEGER      NOT NULL DEFAULT 0,  -- optimistic locking (@Version)
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_rooms_lifecycle ON communities.rooms (lifecycle, scheduled_at);

CREATE TABLE communities.room_tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     BIGINT      NOT NULL REFERENCES communities.rooms (id) ON DELETE CASCADE,
    tag         VARCHAR(40) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_room_tags UNIQUE (room_id, tag)
);

CREATE TABLE communities.participants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     BIGINT      NOT NULL REFERENCES communities.rooms (id) ON DELETE CASCADE,
    alias_id    BIGINT      NOT NULL,
    role        VARCHAR(10) NOT NULL DEFAULT 'LISTENER' CHECK (role IN ('HOST', 'MODERATOR', 'SPEAKER', 'LISTENER')),
    status      VARCHAR(10) NOT NULL DEFAULT 'JOINED' CHECK (status IN ('JOINED', 'LEFT', 'REMOVED')),
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    left_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- An alias can be inside a room only once at a time.
CREATE UNIQUE INDEX ux_participants_present ON communities.participants (room_id, alias_id) WHERE status = 'JOINED';

CREATE TABLE communities.speaker_requests (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id               BIGINT      NOT NULL REFERENCES communities.rooms (id) ON DELETE CASCADE,
    participant_id        BIGINT      NOT NULL REFERENCES communities.participants (id) ON DELETE CASCADE,
    status                VARCHAR(10) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    resolved_by_alias_id  BIGINT,
    requested_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at           TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_speaker_requests_pending ON communities.speaker_requests (participant_id) WHERE status = 'PENDING';

CREATE TABLE communities.reactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id         BIGINT      NOT NULL REFERENCES communities.rooms (id) ON DELETE CASCADE,
    participant_id  BIGINT      NOT NULL REFERENCES communities.participants (id) ON DELETE CASCADE,
    reaction_type   VARCHAR(20) NOT NULL CHECK (reaction_type IN ('VIRTUAL_HUG', 'HEART', 'CLAP', 'SUPPORT')),
    sent_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_reactions_room ON communities.reactions (room_id, sent_at);

CREATE TABLE communities.moderation_cases (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id               BIGINT       NOT NULL REFERENCES communities.rooms (id) ON DELETE CASCADE,
    reporter_alias_id     BIGINT       NOT NULL,
    reported_alias_id     BIGINT       NOT NULL,
    reason                VARCHAR(30)  NOT NULL CHECK (reason IN ('HARASSMENT', 'HATE_SPEECH', 'SELF_HARM_CONTENT', 'SPAM', 'OTHER')),
    description           VARCHAR(1000),
    status                VARCHAR(10)  NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'RESOLVED', 'DISMISSED')),
    action                VARCHAR(10)  CHECK (action IN ('NONE', 'MUTE', 'REMOVE', 'BLOCK')),
    resolved_by_alias_id  BIGINT,
    resolved_at           TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_moderation_cases_distinct CHECK (reporter_alias_id <> reported_alias_id)
);
CREATE INDEX ix_moderation_cases_open ON communities.moderation_cases (room_id) WHERE status = 'OPEN';

CREATE TABLE communities.blocks (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_alias_id    BIGINT      NOT NULL,
    blocked_alias_id    BIGINT      NOT NULL,
    moderation_case_id  BIGINT      REFERENCES communities.moderation_cases (id) ON DELETE SET NULL,
    active              BOOLEAN     NOT NULL DEFAULT TRUE,
    deactivated_at      TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_blocks_distinct CHECK (blocker_alias_id <> blocked_alias_id)
);
CREATE UNIQUE INDEX ux_blocks_active_pair ON communities.blocks (blocker_alias_id, blocked_alias_id) WHERE active;

-- =====================================================================
-- ROUTINES (DailyCare): routines, reminders, writing prompts, SOS exercises
-- =====================================================================

CREATE TABLE routines.routines (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT       NOT NULL,
    routine_type  VARCHAR(20)  NOT NULL DEFAULT 'CUSTOM'
                  CHECK (routine_type IN ('CUSTOM', 'JOURNALING', 'MOOD_CHECK_IN', 'BREATHING')),  -- JOURNALING = diary reminder
    title         VARCHAR(100) NOT NULL,
    description   VARCHAR(500),
    target_time   TIME         NOT NULL,                  -- local time in the profile timezone
    days_of_week  SMALLINT[]   NOT NULL DEFAULT '{1,2,3,4,5,6,7}',
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_routines_days CHECK (days_of_week <@ ARRAY[1,2,3,4,5,6,7]::SMALLINT[] AND cardinality(days_of_week) > 0)
);
CREATE INDEX ix_routines_account ON routines.routines (account_id) WHERE active;

-- "Recordatorio de rutina enviado".
CREATE TABLE routines.scheduled_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id      BIGINT       NOT NULL REFERENCES routines.routines (id) ON DELETE CASCADE,
    scheduled_for   TIMESTAMPTZ  NOT NULL,
    status          VARCHAR(10)  NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'CANCELLED')),
    sent_at         TIMESTAMPTZ,
    failure_reason  VARCHAR(300),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ux_scheduled_notifications UNIQUE (routine_id, scheduled_for)
);
CREATE INDEX ix_scheduled_notifications_due ON routines.scheduled_notifications (scheduled_for) WHERE status = 'PENDING';

-- "Rutina marcada como completada".
CREATE TABLE routines.routine_completions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id    BIGINT      NOT NULL REFERENCES routines.routines (id) ON DELETE CASCADE,
    completed_on  DATE        NOT NULL,
    completed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_routine_completions UNIQUE (routine_id, completed_on)
);

-- "Prompt de escritura (asignado por el psicólogo) recibido / completado".
CREATE TABLE routines.writing_prompts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id              BIGINT        NOT NULL,
    assigned_by_account_id  BIGINT,                       -- NULL = system prompt; otherwise the specialist
    question                VARCHAR(500)  NOT NULL,
    answer_text             TEXT,
    status                  VARCHAR(10)   NOT NULL DEFAULT 'ASSIGNED' CHECK (status IN ('ASSIGNED', 'COMPLETED')),
    assigned_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    answered_at             TIMESTAMPTZ,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_writing_prompts_answer CHECK ((status = 'COMPLETED') = (answer_text IS NOT NULL AND answered_at IS NOT NULL))
);
CREATE INDEX ix_writing_prompts_account ON routines.writing_prompts (account_id, status);

-- "Ejercicio de regulación rápida (SOS / Respiración) iniciado".
CREATE TABLE routines.sos_exercise_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id        BIGINT      NOT NULL,
    exercise_type     VARCHAR(20) NOT NULL CHECK (exercise_type IN ('BREATHING', 'GROUNDING', 'BODY_SCAN')),
    duration_seconds  INTEGER     CHECK (duration_seconds > 0),
    initiated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_sos_exercise_logs_account ON routines.sos_exercise_logs (account_id, initiated_at DESC);
