-- =====================================================================
-- MindCluster / SafeDiary - reference database schema (PostgreSQL 14+)
-- =====================================================================
-- Single source of truth for the target model. Read docs/database/README.md
-- before changing anything here.
--
-- Conventions (summary):
--   * One PostgreSQL schema per bounded context; the context owns its tables.
--   * 8 bounded contexts: iam, profiles, diary, assistantai, rutines,
--     clinician_directory, care_scheduling, payments.
--   * PK: id BIGINT identity (matches AuditableAbstractAggregateRoot).
--   * Every table: created_at / updated_at timestamptz (audit/event logs: only occurred_at).
--   * Enums: VARCHAR + CHECK with UPPER_SNAKE values (same as Java enums).
--   * Foreign keys ONLY inside the same schema. Other contexts are referenced
--     by id (account_id, clinician_profile_id...) without a cross-schema FK.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS iam;
CREATE SCHEMA IF NOT EXISTS profiles;
CREATE SCHEMA IF NOT EXISTS diary;
CREATE SCHEMA IF NOT EXISTS assistantai;
CREATE SCHEMA IF NOT EXISTS rutines;
CREATE SCHEMA IF NOT EXISTS clinician_directory;
CREATE SCHEMA IF NOT EXISTS care_scheduling;
CREATE SCHEMA IF NOT EXISTS payments;

-- =====================================================================
-- 1. IAM: identity, authentication, devices, consents, private vaults and audit
-- =====================================================================

CREATE TABLE iam.accounts (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                  VARCHAR(254) NOT NULL,
    password_hash          VARCHAR(100),                 -- NULL when the account only uses an external provider
    role                   VARCHAR(20)  NOT NULL CHECK (role IN ('PATIENT', 'SPECIALIST', 'ADMIN')),
    status                 VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE'
                           CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED', 'SUSPENDED', 'PENDING_DELETION')),
    failed_login_attempts  SMALLINT     NOT NULL DEFAULT 0 CHECK (failed_login_attempts >= 0),
    locked_until           TIMESTAMPTZ,                  -- policy: 5 failed attempts => temporary lock
    biometric_enabled      BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at          TIMESTAMPTZ,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_accounts_email ON iam.accounts (lower(email));

CREATE TABLE iam.auth_providers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     BIGINT      NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    provider_type  VARCHAR(20) NOT NULL CHECK (provider_type IN ('EMAIL', 'GOOGLE', 'APPLE')),
    external_id    VARCHAR(255) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_auth_providers_external UNIQUE (provider_type, external_id)
);
CREATE INDEX ix_auth_providers_account ON iam.auth_providers (account_id);

-- One row per physical device: biometric unlock + push token live here.
CREATE TABLE iam.devices (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id         BIGINT       NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    device_identifier  VARCHAR(128) NOT NULL,
    platform           VARCHAR(10)  NOT NULL CHECK (platform IN ('ANDROID', 'IOS', 'WEB')),
    push_token         VARCHAR(512),
    biometric_enabled  BOOLEAN      NOT NULL DEFAULT FALSE,
    last_seen_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ux_devices_account_device UNIQUE (account_id, device_identifier)
);

-- Policy: logout invalidates the device token => revoked_at.
CREATE TABLE iam.refresh_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT      NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    device_id    BIGINT      REFERENCES iam.devices (id) ON DELETE CASCADE,
    token_hash   CHAR(64)    NOT NULL UNIQUE,            -- SHA-256, never the raw token
    expires_at   TIMESTAMPTZ NOT NULL,
    revoked_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_refresh_tokens_account ON iam.refresh_tokens (account_id);

-- Policy: single-use link that expires after 30 minutes.
CREATE TABLE iam.password_reset_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT      NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    token_hash   CHAR(64)    NOT NULL UNIQUE,
    expires_at   TIMESTAMPTZ NOT NULL,
    used_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_password_reset_tokens_account ON iam.password_reset_tokens (account_id);

-- Patient -> specialist consent to see the emotional history.
CREATE TABLE iam.consents (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_account_id     BIGINT      NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    specialist_account_id  BIGINT      NOT NULL REFERENCES iam.accounts (id) ON DELETE CASCADE,
    status                 VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED')),
    granted_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at             TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_consents_distinct_accounts CHECK (patient_account_id <> specialist_account_id),
    CONSTRAINT ck_consents_revoked CHECK ((status = 'REVOKED') = (revoked_at IS NOT NULL))
);
CREATE UNIQUE INDEX ux_consents_active_pair ON iam.consents (patient_account_id, specialist_account_id)
    WHERE status = 'ACTIVE';
CREATE INDEX ix_consents_specialist ON iam.consents (specialist_account_id) WHERE status = 'ACTIVE';

-- What the consent covers (sharing permission scope and date period).
CREATE TABLE iam.sharing_permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_id    BIGINT      NOT NULL REFERENCES iam.consents (id) ON DELETE CASCADE,
    scope         VARCHAR(30) NOT NULL CHECK (scope IN ('DIARY_ENTRIES', 'MOOD_CHECK_INS', 'AI_CLINICAL_SUMMARIES')),
    period_start  DATE,
    period_end    DATE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_sharing_permissions_period CHECK (period_end IS NULL OR period_start IS NULL OR period_end >= period_start),
    CONSTRAINT ux_sharing_permissions UNIQUE (consent_id, scope)
);

-- Private vault: protected area unlocked by PIN or biometrics (secures sensitive diary entries).
CREATE TABLE iam.private_vaults (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT       NOT NULL UNIQUE REFERENCES iam.accounts (id) ON DELETE CASCADE,
    pin_hash    VARCHAR(100) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- References to entries in the diary context protected under the private vault.
CREATE TABLE iam.vault_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id        BIGINT      NOT NULL REFERENCES iam.private_vaults (id) ON DELETE CASCADE,
    diary_entry_id  BIGINT      NOT NULL,                -- -> diary.diary_entries (no FK: other context)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_vault_entries UNIQUE (vault_id, diary_entry_id)
);
CREATE INDEX ix_vault_entries_vault ON iam.vault_entries (vault_id);

-- Append-only security audit log (consents, vault access, crisis protocol, logins...). Never UPDATE or DELETE.
CREATE TABLE iam.audit_events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_account_id   BIGINT      REFERENCES iam.accounts (id) ON DELETE SET NULL,  -- NULL when the system acts
    target_account_id  BIGINT      REFERENCES iam.accounts (id) ON DELETE SET NULL,
    consent_id         BIGINT      REFERENCES iam.consents (id) ON DELETE SET NULL,
    action             VARCHAR(60) NOT NULL,             -- CONSENT_GRANTED, CONSENT_REVOKED, VAULT_UNLOCKED, ACCESS_GRANTED...
    source_context     VARCHAR(30) NOT NULL,             -- iam, profiles, diary, assistantai, rutines, clinician_directory, care_scheduling, payments
    resource_type      VARCHAR(60),
    resource_id        BIGINT,
    metadata           JSONB,
    occurred_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_events_target ON iam.audit_events (target_account_id, occurred_at DESC);
CREATE INDEX ix_audit_events_consent ON iam.audit_events (consent_id);

-- =====================================================================
-- 2. PROFILES: personal profile, preferences, bookmarks, plan projection
-- =====================================================================

-- Created automatically when IAM publishes "UserAccountRegistered".
CREATE TABLE profiles.user_profiles (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id                   BIGINT       NOT NULL UNIQUE,   -- -> iam.accounts (no FK: other context)
    display_name                 VARCHAR(80)  NOT NULL,
    avatar_url                   VARCHAR(512),
    birth_date                   DATE,
    locale                       VARCHAR(10)  NOT NULL DEFAULT 'es-PE',
    timezone                     VARCHAR(40)  NOT NULL DEFAULT 'America/Lima',
    created_at                   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- App preferences: notification configuration and assistant tone.
CREATE TABLE profiles.app_preferences (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id            BIGINT      NOT NULL UNIQUE REFERENCES profiles.user_profiles (id) ON DELETE CASCADE,
    notifications_enabled BOOLEAN     NOT NULL DEFAULT TRUE,
    push_enabled          BOOLEAN     NOT NULL DEFAULT TRUE,
    email_enabled         BOOLEAN     NOT NULL DEFAULT FALSE,
    assistant_tone        VARCHAR(20) NOT NULL DEFAULT 'EMPATHIC'
                          CHECK (assistant_tone IN ('EMPATHIC', 'REFLECTIVE', 'ANALYTICAL', 'CALM')),
    quiet_hours_start     TIME,
    quiet_hours_end       TIME,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Specialists bookmarked / saved by a user.
CREATE TABLE profiles.bookmarked_clinicians (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id    BIGINT      NOT NULL REFERENCES profiles.user_profiles (id) ON DELETE CASCADE,
    clinician_id  BIGINT      NOT NULL,                          -- -> clinician_directory.clinician_profiles (no FK: other context)
    saved_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_bookmarked_clinicians UNIQUE (profile_id, clinician_id)
);
CREATE INDEX ix_bookmarked_clinicians_profile ON profiles.bookmarked_clinicians (profile_id);

-- Read model projection of subscription plan updated via Payments domain events.
CREATE TABLE profiles.plan_status_projections (
    account_id       BIGINT      PRIMARY KEY,                    -- -> iam.accounts (no FK: other context)
    plan             VARCHAR(20) NOT NULL DEFAULT 'BASICO'
                     CHECK (plan IN ('BASICO', 'PREMIUM')),
    source_event_id  VARCHAR(128) UNIQUE,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================================================================
-- 3. DIARY: entries (text/voice), tags, factors, attachments, mood, streaks
-- =====================================================================

CREATE TABLE diary.diary_entries (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id              BIGINT       NOT NULL,               -- -> iam.accounts (no FK: other context)
    title                   VARCHAR(150),
    content                 TEXT,                                -- text body or transcript of a voice entry
    entry_type              VARCHAR(10)  NOT NULL CHECK (entry_type IN ('TEXT', 'AUDIO', 'HYBRID', 'VOICE')),
    audio_url               VARCHAR(512),
    audio_duration_seconds  INTEGER      CHECK (audio_duration_seconds > 0),
    transcription_status    VARCHAR(20)  CHECK (transcription_status IN ('PENDING', 'COMPLETED', 'FAILED')),
    primary_emotion         VARCHAR(20)  CHECK (primary_emotion IN
                            ('JOY', 'SADNESS', 'ANXIETY', 'ANGER', 'CALM', 'FEAR', 'SURPRISE', 'DISGUST',
                             'APPREHENSION', 'ACCEPTANCE', 'ANNOYANCE', 'VIGILANCE', 'PENSIVENESS', 'SERENITY')),
    emotion_confirmed       BOOLEAN      NOT NULL DEFAULT FALSE, -- AI-suggested until confirmed by user
    emotional_intensity     SMALLINT     CHECK (emotional_intensity BETWEEN 1 AND 10),
    ai_reflection           TEXT,                                -- filled by reflection event from AssistantAI
    is_sensitive            BOOLEAN      NOT NULL DEFAULT FALSE,
    is_vaulted              BOOLEAN      NOT NULL DEFAULT FALSE, -- true if protected in iam.private_vaults
    status                  VARCHAR(10)  NOT NULL DEFAULT 'SAVED'
                            CHECK (status IN ('DRAFT', 'SAVED', 'PUBLISHED', 'ARCHIVED', 'DELETED')),
    written_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_diary_entries_body CHECK (
        (entry_type = 'TEXT' AND content IS NOT NULL) OR
        (entry_type IN ('AUDIO', 'VOICE') AND audio_url IS NOT NULL) OR
        (entry_type = 'HYBRID' AND (content IS NOT NULL OR audio_url IS NOT NULL)))
);
CREATE INDEX ix_diary_entries_account_written ON diary.diary_entries (account_id, written_at DESC)
    WHERE status <> 'DELETED';

CREATE TABLE diary.entry_tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id    BIGINT      NOT NULL REFERENCES diary.diary_entries (id) ON DELETE CASCADE,
    tag_name    VARCHAR(40) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_entry_tags UNIQUE (entry_id, tag_name)
);

-- External context factors (sleep, energy, stress, weather, caffeine).
CREATE TABLE diary.external_factors (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id         BIGINT       NOT NULL UNIQUE REFERENCES diary.diary_entries (id) ON DELETE CASCADE,
    sleep_hours      NUMERIC(3, 1) CHECK (sleep_hours BETWEEN 0 AND 24),
    energy_level     VARCHAR(10)  CHECK (energy_level IN ('LOW', 'MEDIUM', 'HIGH')),
    stress_level     VARCHAR(10)  CHECK (stress_level IN ('LOW', 'MEDIUM', 'HIGH')),
    weather          VARCHAR(20)  CHECK (weather IN ('SUNNY', 'CLOUDY', 'RAINY', 'COLD', 'HOT')),
    caffeine_intake  VARCHAR(10)  CHECK (caffeine_intake IN ('NONE', 'LOW', 'MODERATE', 'MEDIUM', 'HIGH')),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Multimedia files associated with diary entries.
CREATE TABLE diary.entry_attachments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id    BIGINT       NOT NULL REFERENCES diary.diary_entries (id) ON DELETE CASCADE,
    file_url    VARCHAR(512) NOT NULL,
    media_type  VARCHAR(100) NOT NULL,                           -- MIME type
    size_bytes  BIGINT       NOT NULL CHECK (size_bytes > 0),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_entry_attachments_entry ON diary.entry_attachments (entry_id);

-- One-touch daily mood log.
CREATE TABLE diary.mood_check_ins (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     BIGINT      NOT NULL,                         -- -> iam.accounts (no FK: other context)
    emotion        VARCHAR(20) NOT NULL,
    valence_score  SMALLINT    NOT NULL CHECK (valence_score BETWEEN -5 AND 5),
    energy_score   SMALLINT    CHECK (energy_score BETWEEN 1 AND 10),
    logged_on      DATE        NOT NULL,
    logged_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_mood_check_ins_daily UNIQUE (account_id, logged_on)
);

-- Scheduled alarms specifically to encourage journaling habits.
CREATE TABLE diary.diary_reminders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT      NOT NULL,                          -- -> iam.accounts (no FK: other context)
    reminder_time TIME        NOT NULL,
    days_of_week  VARCHAR(50) NOT NULL DEFAULT '1,2,3,4,5,6,7',
    is_enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_diary_reminders_account ON diary.diary_reminders (account_id);

CREATE TABLE diary.streaks (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id              BIGINT      NOT NULL UNIQUE,         -- -> iam.accounts (no FK: other context)
    current_streak_days     INTEGER     NOT NULL DEFAULT 0 CHECK (current_streak_days >= 0),
    longest_streak_days     INTEGER     NOT NULL DEFAULT 0 CHECK (longest_streak_days >= 0),
    last_log_date           DATE,
    freeze_tokens_available SMALLINT    NOT NULL DEFAULT 0 CHECK (freeze_tokens_available >= 0),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE diary.badges (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT      NOT NULL,                           -- -> iam.accounts (no FK: other context)
    badge_type   VARCHAR(30) NOT NULL
                 CHECK (badge_type IN ('STREAK_7', 'STREAK_30', 'STREAK_100', 'FIRST_VOICE_NOTE', 'FIRST_ENTRY')),
    unlocked_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_badges UNIQUE (account_id, badge_type)
);

-- =====================================================================
-- 4. ASSISTANTAI: conversations, emotions, distortions, risk assessments
-- (Matches Spring Data JPA entities under assistantai.infrastructure.persistence)
-- =====================================================================

CREATE TABLE assistantai.conversation_sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT      NOT NULL,                          -- -> iam.accounts (no FK: other context)
    title         VARCHAR(80),                                   -- matches ConversationSessionPersistenceEntity.title
    started_at    TIMESTAMPTZ NOT NULL,
    ended_at      TIMESTAMPTZ,
    status        VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'CLOSED', 'CRISIS_TRIGGERED')),
    current_tone  VARCHAR(20) NOT NULL CHECK (current_tone IN ('EMPATHIC', 'REFLECTIVE', 'ANALYTICAL', 'CALM')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_conversation_sessions_account ON assistantai.conversation_sessions (account_id, started_at DESC);

CREATE TABLE assistantai.conversation_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT      NOT NULL REFERENCES assistantai.conversation_sessions (id) ON DELETE CASCADE,
    sender       VARCHAR(10) NOT NULL CHECK (sender IN ('USER', 'AI')),
    content      TEXT        NOT NULL,
    emotion_tag  VARCHAR(20) CHECK (emotion_tag IN
                 ('APPREHENSION', 'ACCEPTANCE', 'ANNOYANCE', 'VIGILANCE', 'PENSIVENESS', 'SERENITY', 'JOY', 'SADNESS', 'FEAR')),
    sent_at      TIMESTAMPTZ NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_conversation_messages_session ON assistantai.conversation_messages (session_id, sent_at);

CREATE TABLE assistantai.cognitive_distortions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT       NOT NULL REFERENCES assistantai.conversation_messages (id) ON DELETE CASCADE,
    type        VARCHAR(30)  NOT NULL CHECK (type IN
                ('CATASTROPHIZING', 'OVERGENERALIZATION', 'ALL_OR_NOTHING', 'EMOTIONAL_REASONING', 'MENTAL_FILTER')),
    evidence    VARCHAR(300),
    confidence  DOUBLE PRECISION NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_cognitive_distortions_message ON assistantai.cognitive_distortions (message_id);

-- One assessment per evaluated session (matches RiskAssessmentPersistenceEntity: sessionId, riskScore, riskLevel, triggerKeywords, crisisProtocolActivated, assessedAt).
CREATE TABLE assistantai.risk_assessments (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id                 BIGINT       NOT NULL REFERENCES assistantai.conversation_sessions (id) ON DELETE CASCADE,
    risk_score                 DOUBLE PRECISION NOT NULL CHECK (risk_score BETWEEN 0 AND 1),
    risk_level                 VARCHAR(10)  NOT NULL CHECK (risk_level IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')),
    trigger_keywords           VARCHAR(500),
    crisis_protocol_activated  BOOLEAN      NOT NULL DEFAULT FALSE,
    assessed_at                TIMESTAMPTZ  NOT NULL,
    created_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                 TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_risk_assessments_session ON assistantai.risk_assessments (session_id, assessed_at DESC);
CREATE INDEX ix_risk_assessments_crisis ON assistantai.risk_assessments (assessed_at DESC)
    WHERE crisis_protocol_activated;

-- Planned table: weekly synthesis for the specialist (matches ClinicalSummaryPersistenceEntity JPA entity and doc).
CREATE TABLE assistantai.clinical_summaries (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id           BIGINT       NOT NULL,                  -- -> iam.accounts (no FK: other context)
    period_start         DATE         NOT NULL,
    period_end           DATE         NOT NULL,
    dominant_emotions    VARCHAR(200),
    key_triggers         TEXT,
    synthesis_narrative  TEXT         NOT NULL,
    highlights           TEXT,
    generated_at         TIMESTAMPTZ  NOT NULL,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_clinical_summaries_period CHECK (period_end >= period_start),
    CONSTRAINT ux_clinical_summaries_period UNIQUE (account_id, period_start, period_end)
);

-- =====================================================================
-- 5. RUTINES: routines, scheduled notifications, completions, SOS exercises
-- =====================================================================

CREATE TABLE rutines.routines (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT       NOT NULL,                         -- -> iam.accounts (no FK: other context)
    routine_type  VARCHAR(20)  NOT NULL DEFAULT 'CUSTOM'
                  CHECK (routine_type IN ('CUSTOM', 'JOURNALING', 'MOOD_CHECK_IN', 'BREATHING')),
    title         VARCHAR(100) NOT NULL,
    description   VARCHAR(500),
    target_time   TIME         NOT NULL,                         -- local time in user's profile timezone
    days_of_week  SMALLINT[]   NOT NULL DEFAULT '{1,2,3,4,5,6,7}',
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_routines_days CHECK (days_of_week <@ ARRAY[1,2,3,4,5,6,7]::SMALLINT[] AND cardinality(days_of_week) > 0)
);
CREATE INDEX ix_routines_account ON rutines.routines (account_id) WHERE active;

CREATE TABLE rutines.scheduled_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id      BIGINT       NOT NULL REFERENCES rutines.routines (id) ON DELETE CASCADE,
    scheduled_for   TIMESTAMPTZ  NOT NULL,
    status          VARCHAR(10)  NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'CANCELLED')),
    sent_at         TIMESTAMPTZ,
    failure_reason  VARCHAR(300),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ux_scheduled_notifications UNIQUE (routine_id, scheduled_for)
);
CREATE INDEX ix_scheduled_notifications_due ON rutines.scheduled_notifications (scheduled_for) WHERE status = 'PENDING';

CREATE TABLE rutines.routine_completions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id    BIGINT      NOT NULL REFERENCES rutines.routines (id) ON DELETE CASCADE,
    completed_on  DATE        NOT NULL,
    completed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_routine_completions UNIQUE (routine_id, completed_on)
);

CREATE TABLE rutines.writing_prompts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id              BIGINT        NOT NULL,                  -- -> iam.accounts (no FK: other context)
    assigned_by_account_id  BIGINT,                                  -- NULL = system prompt; otherwise clinician -> iam.accounts
    question                VARCHAR(500)  NOT NULL,
    answer_text             TEXT,
    status                  VARCHAR(10)   NOT NULL DEFAULT 'ASSIGNED' CHECK (status IN ('ASSIGNED', 'COMPLETED')),
    assigned_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    answered_at             TIMESTAMPTZ,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_writing_prompts_answer CHECK ((status = 'COMPLETED') = (answer_text IS NOT NULL AND answered_at IS NOT NULL))
);
CREATE INDEX ix_writing_prompts_account ON rutines.writing_prompts (account_id, status);

CREATE TABLE rutines.sos_exercise_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id        BIGINT      NOT NULL,                          -- -> iam.accounts (no FK: other context)
    exercise_type     VARCHAR(20) NOT NULL CHECK (exercise_type IN ('BREATHING', 'GROUNDING', 'BODY_SCAN')),
    duration_seconds  INTEGER     CHECK (duration_seconds > 0),
    initiated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_sos_exercise_logs_account ON rutines.sos_exercise_logs (account_id, initiated_at DESC);

-- =====================================================================
-- 6. CLINICIAN DIRECTORY: verified profile, specialties, rates, reviews, trust
-- =====================================================================

CREATE TABLE clinician_directory.clinician_profiles (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id           BIGINT       NOT NULL UNIQUE,               -- -> iam.accounts (no FK: other context)
    professional_title   VARCHAR(120),
    bio                  TEXT,
    banner_ref           VARCHAR(512),
    verification_status  VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                         CHECK (verification_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    publication_status   VARCHAR(20)  NOT NULL DEFAULT 'DRAFT'
                         CHECK (publication_status IN ('DRAFT', 'PUBLISHED', 'HIDDEN')),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_clinician_profiles_search ON clinician_directory.clinician_profiles (verification_status, publication_status);

CREATE TABLE clinician_directory.clinician_specialties (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_profile_id  BIGINT       NOT NULL REFERENCES clinician_directory.clinician_profiles (id) ON DELETE CASCADE,
    specialty_name        VARCHAR(100) NOT NULL,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ux_clinician_specialties UNIQUE (clinician_profile_id, specialty_name)
);
CREATE INDEX ix_clinician_specialties_name ON clinician_directory.clinician_specialties (lower(specialty_name));

-- Professional credential review requests submitted to platform administration.
CREATE TABLE clinician_directory.verification_requests (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_profile_id    BIGINT       NOT NULL REFERENCES clinician_directory.clinician_profiles (id) ON DELETE CASCADE,
    document_ref            VARCHAR(512) NOT NULL,                   -- private document storage URI
    status                  VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                            CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    rejection_reason        VARCHAR(500),
    submitted_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    reviewed_by_account_id  BIGINT,                                  -- -> iam.accounts (admin reviewer, no FK)
    reviewed_at             TIMESTAMPTZ,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_verification_requests_clinician ON clinician_directory.verification_requests (clinician_profile_id, submitted_at DESC);

-- Published consultation pricing and session duration.
CREATE TABLE clinician_directory.consultation_rates (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_profile_id  BIGINT         NOT NULL REFERENCES clinician_directory.clinician_profiles (id) ON DELETE CASCADE,
    amount                NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
    currency              CHAR(3)        NOT NULL DEFAULT 'PEN',
    duration_minutes      SMALLINT       NOT NULL DEFAULT 50 CHECK (duration_minutes > 0),
    effective_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    is_active             BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ    NOT NULL DEFAULT now()
);
CREATE INDEX ix_consultation_rates_active ON clinician_directory.consultation_rates (clinician_profile_id) WHERE is_active;

-- Patient reviews eligible only upon completion of a Care Scheduling session.
CREATE TABLE clinician_directory.reviews (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_profile_id  BIGINT      NOT NULL REFERENCES clinician_directory.clinician_profiles (id) ON DELETE CASCADE,
    appointment_id        BIGINT      NOT NULL UNIQUE,               -- -> care_scheduling.appointments (no FK: other context)
    patient_account_id    BIGINT      NOT NULL,                      -- -> iam.accounts (no FK: other context)
    rating                SMALLINT    NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text           TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_reviews_clinician ON clinician_directory.reviews (clinician_profile_id, created_at DESC);

-- Read model: aggregate rating summary.
CREATE TABLE clinician_directory.rating_summaries (
    clinician_profile_id  BIGINT        PRIMARY KEY REFERENCES clinician_directory.clinician_profiles (id) ON DELETE CASCADE,
    average               NUMERIC(3, 2) NOT NULL DEFAULT 0.00 CHECK (average BETWEEN 0 AND 5),
    review_count          INTEGER       NOT NULL DEFAULT 0 CHECK (review_count >= 0),
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Read model: verifiable trust score explaining confidence factors.
CREATE TABLE clinician_directory.trust_scores (
    clinician_profile_id  BIGINT        PRIMARY KEY REFERENCES clinician_directory.clinician_profiles (id) ON DELETE CASCADE,
    score                 NUMERIC(5, 2) NOT NULL DEFAULT 0.00 CHECK (score BETWEEN 0 AND 100),
    factor_breakdown      JSONB,
    sufficient_data       BOOLEAN       NOT NULL DEFAULT FALSE,
    calculated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- =====================================================================
-- 7. CARE SCHEDULING: contact requests, slots, appointments, holds, sessions
-- =====================================================================

-- Initial contact and coordination initiation between patient and psychologist.
CREATE TABLE care_scheduling.contact_requests (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_account_id    BIGINT      NOT NULL,                      -- -> iam.accounts (no FK: other context)
    clinician_profile_id  BIGINT      NOT NULL,                      -- -> clinician_directory.clinician_profiles (no FK: other context)
    status                VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                          CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CLOSED')),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_contact_requests_patient ON care_scheduling.contact_requests (patient_account_id);
CREATE INDEX ix_contact_requests_clinician ON care_scheduling.contact_requests (clinician_profile_id);

-- Direct scheduling coordination chat (does not grant diary access).
CREATE TABLE care_scheduling.coordination_messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_request_id  BIGINT      NOT NULL REFERENCES care_scheduling.contact_requests (id) ON DELETE CASCADE,
    sender_account_id   BIGINT      NOT NULL,                        -- -> iam.accounts (no FK: other context)
    body_text           TEXT        NOT NULL,
    sent_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_coordination_messages_request ON care_scheduling.coordination_messages (contact_request_id, sent_at);

-- Clinician recurring weekly bookable availability slots.
CREATE TABLE care_scheduling.availability_slots (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_profile_id  BIGINT      NOT NULL,                      -- -> clinician_directory.clinician_profiles (no FK: other context)
    day_of_week           SMALLINT    NOT NULL CHECK (day_of_week BETWEEN 1 AND 7), -- ISO: 1 = Monday
    start_time            TIME        NOT NULL,
    end_time              TIME        NOT NULL,
    is_active             BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_care_slot_time CHECK (end_time > start_time)
);
CREATE INDEX ix_availability_slots_clinician ON care_scheduling.availability_slots (clinician_profile_id) WHERE is_active;

-- Appointments: holds agreed schedule, amount captured, and confirmation status.
CREATE TABLE care_scheduling.appointments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_request_id    BIGINT         REFERENCES care_scheduling.contact_requests (id) ON DELETE SET NULL,
    patient_account_id    BIGINT         NOT NULL,                   -- -> iam.accounts (no FK: other context)
    clinician_profile_id  BIGINT         NOT NULL,                   -- -> clinician_directory.clinician_profiles (no FK: other context)
    starts_at             TIMESTAMPTZ    NOT NULL,
    ends_at               TIMESTAMPTZ    NOT NULL,
    timezone              VARCHAR(40)    NOT NULL DEFAULT 'America/Lima',
    agreed_amount         NUMERIC(10, 2) NOT NULL CHECK (agreed_amount >= 0),
    currency              CHAR(3)        NOT NULL DEFAULT 'PEN',
    status                VARCHAR(20)    NOT NULL DEFAULT 'REQUESTED'
                          CHECK (status IN ('REQUESTED', 'HELD', 'CONFIRMED', 'CANCELLED', 'EXPIRED', 'COMPLETED')),
    payment_reference     VARCHAR(128),                              -- -> payments.payment_intents (no FK: other context)
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT ck_appointment_time CHECK (ends_at > starts_at)
);
CREATE INDEX ix_appointments_clinician_time ON care_scheduling.appointments (clinician_profile_id, starts_at);
CREATE INDEX ix_appointments_patient ON care_scheduling.appointments (patient_account_id, starts_at DESC);

-- Temporary 1-hour reservation hold pending payment confirmation.
CREATE TABLE care_scheduling.slot_holds (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id  BIGINT      NOT NULL UNIQUE REFERENCES care_scheduling.appointments (id) ON DELETE CASCADE,
    expires_at      TIMESTAMPTZ NOT NULL,                            -- policy: holds slot for 60 minutes
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                    CHECK (status IN ('ACTIVE', 'EXPIRED', 'RELEASED', 'CONFIRMED')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_slot_holds_active ON care_scheduling.slot_holds (expires_at) WHERE status = 'ACTIVE';

-- Execution and video call session for confirmed appointments.
CREATE TABLE care_scheduling.clinical_sessions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id     BIGINT       NOT NULL UNIQUE REFERENCES care_scheduling.appointments (id) ON DELETE CASCADE,
    provider_room_ref  VARCHAR(255),                                 -- WebRTC / video provider room identifier
    started_at         TIMESTAMPTZ,
    ended_at           TIMESTAMPTZ,
    status             VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED'
                       CHECK (status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'NO_SHOW', 'CANCELLED')),
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Access audit log for authorized emotional summaries retrieved prior to a session.
CREATE TABLE care_scheduling.summary_access_audits (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id        BIGINT       NOT NULL REFERENCES care_scheduling.appointments (id) ON DELETE CASCADE,
    clinician_account_id  BIGINT       NOT NULL,                     -- -> iam.accounts (no FK: other context)
    consent_ref           VARCHAR(128) NOT NULL,                     -- verified active IAM consent reference
    accessed_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- =====================================================================
-- 8. PAYMENTS & PAYOUTS: payment intents, subscriptions, ledger, payouts
-- =====================================================================

-- Idempotent payment charges for sessions or Premium subscriptions.
CREATE TABLE payments.payment_intents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purpose             VARCHAR(20)    NOT NULL CHECK (purpose IN ('APPOINTMENT', 'SUBSCRIPTION')),
    subject_id          BIGINT         NOT NULL,                     -- appointment_id or subscription_id (no FK: other context)
    payer_account_id    BIGINT         NOT NULL,                     -- -> iam.accounts (patient) (no FK: other context)
    amount              NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
    currency            CHAR(3)        NOT NULL DEFAULT 'PEN',
    idempotency_key     VARCHAR(128)   NOT NULL UNIQUE,
    provider_reference  VARCHAR(255)   UNIQUE,
    status              VARCHAR(20)    NOT NULL DEFAULT 'CREATED'
                        CHECK (status IN ('CREATED', 'PENDING', 'APPROVED', 'FAILED', 'REFUNDED')),
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now()
);
CREATE INDEX ix_payment_intents_subject ON payments.payment_intents (purpose, subject_id);
CREATE INDEX ix_payment_intents_payer ON payments.payment_intents (payer_account_id, created_at DESC);

-- Premium subscription status and validity period for patients.
CREATE TABLE payments.subscriptions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_account_id  BIGINT      NOT NULL UNIQUE,                 -- -> iam.accounts (no FK: other context)
    plan                VARCHAR(20) NOT NULL DEFAULT 'BASICO'
                        CHECK (plan IN ('BASICO', 'PREMIUM')),
    active_until        TIMESTAMPTZ,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Official payment receipts issued upon approved payment intents.
CREATE TABLE payments.receipts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_intent_id  BIGINT       NOT NULL UNIQUE REFERENCES payments.payment_intents (id) ON DELETE CASCADE,
    receipt_number     VARCHAR(64)  NOT NULL UNIQUE,
    file_ref           VARCHAR(512),
    issued_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Financial movements ledger for psychologist session income and platform commissions.
CREATE TABLE payments.professional_ledger_movements (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_account_id  BIGINT         NOT NULL,                   -- -> iam.accounts (specialist) (no FK: other context)
    appointment_id        BIGINT         NOT NULL,                   -- -> care_scheduling.appointments (no FK: other context)
    gross_amount          NUMERIC(10, 2) NOT NULL CHECK (gross_amount >= 0),
    commission_amount     NUMERIC(10, 2) NOT NULL CHECK (commission_amount >= 0),
    net_amount            NUMERIC(10, 2) NOT NULL CHECK (net_amount >= 0),
    status                VARCHAR(20)    NOT NULL DEFAULT 'PENDING'
                          CHECK (status IN ('PENDING', 'AVAILABLE', 'WITHDRAWN')),
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT ck_ledger_amounts CHECK (gross_amount = commission_amount + net_amount)
);
CREATE INDEX ix_ledger_clinician_status ON payments.professional_ledger_movements (clinician_account_id, status);

-- Tokenized payout accounts registered by psychologists.
CREATE TABLE payments.payout_methods (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_account_id  BIGINT       NOT NULL,                     -- -> iam.accounts (specialist) (no FK: other context)
    provider_token_ref    VARCHAR(255) NOT NULL,
    bank_name             VARCHAR(100),
    account_masked        VARCHAR(30),
    status                VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_payout_methods_clinician ON payments.payout_methods (clinician_account_id) WHERE status = 'ACTIVE';

-- Payout requests from clinician available ledger balance.
CREATE TABLE payments.payout_requests (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinician_account_id  BIGINT         NOT NULL,                   -- -> iam.accounts (specialist) (no FK: other context)
    payout_method_id      BIGINT         NOT NULL REFERENCES payments.payout_methods (id) ON DELETE RESTRICT,
    amount                NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
    currency              CHAR(3)        NOT NULL DEFAULT 'PEN',
    status                VARCHAR(20)    NOT NULL DEFAULT 'REQUESTED'
                          CHECK (status IN ('REQUESTED', 'PROCESSING', 'COMPLETED', 'REJECTED')),
    provider_reference    VARCHAR(255),
    requested_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    processed_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ    NOT NULL DEFAULT now()
);
CREATE INDEX ix_payout_requests_clinician ON payments.payout_requests (clinician_account_id, requested_at DESC);
